tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule

env:
  - name:  FLUENT_ELASTICSEARCH_HOST
    value: "elasticsearch.default.svc.cluster.local"
  - name:  FLUENT_ELASTICSEARCH_PORT
    value: "9200"
  - name: FLUENT_ELASTICSEARCH_SCHEME
    value: "http"
  - name: FLUENTD_SYSTEMD_CONF
    value: disable

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 200Mi

volumes:
- name: varlog
  hostPath:
    path: /var/log
- name: varlibdockercontainers
  hostPath:
    path: /var/lib/docker/containers


volumeMounts:
- name: varlog
  mountPath: /var/log
- name: varlibdockercontainers
  mountPath: /var/lib/docker/containers
  readOnly: true

dashboards:
  enabled: "false"